package com.fine.serviceIMPL.stock;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.fine.Dao.purchase.PurchaseOrderItemMapper;
import com.fine.Dao.purchase.PurchaseOrderMapper;
import com.fine.Dao.rd.TapeFormulaMapper;
import com.fine.Dao.schedule.ManualScheduleMapper;
import com.fine.Dao.stock.*;
import com.fine.modle.PurchaseOrder;
import com.fine.modle.PurchaseOrderItem;
import com.fine.model.stock.*;
import com.fine.model.stock.enums.ChemicalRequisitionStatus;
import com.fine.modle.rd.TapeFormula;
import com.fine.modle.rd.TapeFormulaItem;
import com.fine.service.stock.ChemicalRequisitionService;
import com.fine.service.stock.ChemicalStockService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Service
public class ChemicalRequisitionServiceImpl implements ChemicalRequisitionService {

    @Autowired
    private ManualScheduleMapper manualScheduleMapper;
    @Autowired
    private TapeFormulaMapper tapeFormulaMapper;
    @Autowired
    private ChemicalStockMapper chemicalStockMapper;
    @Autowired
    private ChemicalMaterialLockMapper chemicalMaterialLockMapper;
    @Autowired
    private ChemicalPurchaseRequestMapper chemicalPurchaseRequestMapper;
    @Autowired
    private ChemicalPurchaseRequestItemMapper chemicalPurchaseRequestItemMapper;

    @Autowired
    private PurchaseOrderMapper purchaseOrderMapper;

    @Autowired
    private PurchaseOrderItemMapper purchaseOrderItemMapper;

    @Autowired
    private ChemicalRequisitionLogMapper chemicalRequisitionLogMapper;

    @Autowired
    private ChemicalStockService chemicalStockService;

    @Override
    @Transactional(rollbackFor = Exception.class)
    public Map<String, Object> generateFromCoatingPlan(LocalDate planDate, String orderNo, String materialCode) {
        LocalDate targetDate = planDate == null ? LocalDate.now() : planDate;
        List<Map<String, Object>> plans = manualScheduleMapper.selectCoatingPlansForChemical(targetDate, trim(orderNo), trim(materialCode));

        int lockCount = 0;
        int reqCount = 0;
        Set<String> requestNos = new LinkedHashSet<>();
        List<Map<String, Object>> missingFormulaPlans = new ArrayList<>();

        if (plans == null || plans.isEmpty()) {
            return resultMap(0, 0, requestNos, missingFormulaPlans);
        }

        for (Map<String, Object> plan : plans) {
            Long scheduleId = toLong(plan.get("schedule_id"));
            String oNo = str(plan.get("order_no"));
            String finishedCode = str(plan.get("material_code"));
            String finishedName = str(plan.get("material_name"));
            BigDecimal coatingArea = toDecimal(plan.get("coating_area"));
            if (finishedCode == null || coatingArea.compareTo(BigDecimal.ZERO) <= 0) {
                continue;
            }

            TapeFormula formula = tapeFormulaMapper.selectByMaterialCode(finishedCode);
            if (formula == null || formula.getId() == null || formula.getCoatingArea() == null || formula.getCoatingArea().compareTo(BigDecimal.ZERO) <= 0) {
                missingFormulaPlans.add(buildMissingFormulaRow(scheduleId, oNo, finishedCode, finishedName, "配胶单缺失或标准涂布面积未配置"));
                continue;
            }
            List<TapeFormulaItem> items = tapeFormulaMapper.selectItemsByFormulaId(formula.getId());
            if (items == null || items.isEmpty()) {
                missingFormulaPlans.add(buildMissingFormulaRow(scheduleId, oNo, finishedCode, finishedName, "配胶单明细为空"));
                continue;
            }

            ChemicalPurchaseRequest req = ensureDraftRequest(targetDate, scheduleId, oNo, finishedCode);
            requestNos.add(req.getRequestNo());

            // 若已发生过领料(ALLOCATED)，则不再重复分解/请购，避免重复单据
            if (hasAllocatedAutoLocks(scheduleId, oNo, finishedCode)) {
                continue;
            }

            // 幂等处理：同一排程重复查询时，先回滚并清理历史自动生成记录，再重新计算
            cleanupAutoGeneratedForSchedule(req.getId(), scheduleId, oNo, finishedCode);

            BigDecimal factor = coatingArea.divide(formula.getCoatingArea(), 8, RoundingMode.HALF_UP);
            BigDecimal totalWeight = formula.getTotalWeight() == null ? BigDecimal.ZERO : formula.getTotalWeight();

            for (TapeFormulaItem item : items) {
                String rawCode = item == null ? null : trim(item.getMaterialCode());
                if (rawCode == null) {
                    continue;
                }
                String rawName = item == null ? null : str(item.getMaterialName());

                BigDecimal needKg = calcNeedKg(item, factor, totalWeight);
                if (needKg.compareTo(BigDecimal.ZERO) <= 0) {
                    continue;
                }

                ChemicalStock stock = pickChemicalStock(rawCode);
                int requiredQty = convertKgToQty(needKg, stock);
                int lockedQty = 0;
                Long stockId = null;
                String status = "PENDING";

                if (stock != null && requiredQty > 0) {
                    int canLock = Math.min(requiredQty, stock.getAvailableQuantity() == null ? 0 : stock.getAvailableQuantity());
                    if (canLock > 0) {
                        int ok = chemicalStockMapper.lockStock(stock.getId(), canLock);
                        if (ok > 0) {
                            lockedQty = canLock;
                            stockId = stock.getId();
                            status = lockedQty >= requiredQty ? "LOCKED" : "PARTIAL";
                            lockCount++;
                        }
                    }
                }

                ChemicalMaterialLock lock = new ChemicalMaterialLock();
                lock.setPlanDate(Date.from(targetDate.atStartOfDay(ZoneId.systemDefault()).toInstant()));
                lock.setScheduleId(scheduleId);
                lock.setOrderNo(oNo);
                lock.setFinishedMaterialCode(finishedCode);
                lock.setRawMaterialCode(rawCode);
                lock.setRawMaterialName(rawName);
                lock.setChemicalStockId(stockId);
                lock.setRequiredKg(needKg);
                lock.setRequiredQty(requiredQty);
                lock.setLockedQty(lockedQty);
                lock.setLockStatus(status);
                lock.setSourceRef("formulaId=" + formula.getId() + ";finished=" + finishedName);
                lock.setRemark("auto-generate-on-lock-query");
                lock.setCreateTime(new Date());
                lock.setUpdateTime(new Date());
                chemicalMaterialLockMapper.insert(lock);

                if (requiredQty > lockedQty) {
                    int shortage = requiredQty - lockedQty;
                    ChemicalPurchaseRequestItem reqItem = new ChemicalPurchaseRequestItem();
                    reqItem.setRequestId(req.getId());
                    reqItem.setScheduleId(scheduleId);
                    reqItem.setOrderNo(oNo);
                    reqItem.setFinishedMaterialCode(finishedCode);
                    reqItem.setRawMaterialCode(rawCode);
                    reqItem.setRawMaterialName(rawName);
                    reqItem.setRequiredKg(needKg);
                    reqItem.setSuggestedQty(shortage);
                    reqItem.setRequestedQty(shortage);
                    reqItem.setUnit(stock != null && stock.getUnit() != null ? stock.getUnit() : "桶");
                    reqItem.setRemark("库存不足自动请购");
                    reqItem.setCreateTime(new Date());
                    reqItem.setUpdateTime(new Date());
                    chemicalPurchaseRequestItemMapper.insert(reqItem);
                    reqCount++;
                }
            }
        }

        return resultMap(lockCount, reqCount, requestNos, missingFormulaPlans);
    }

    @Override
    public List<Map<String, Object>> queryLocksByPlan(LocalDate planDate, String orderNo, String materialCode) {
        LocalDate targetDate = planDate == null ? LocalDate.now() : planDate;

        QueryWrapper<ChemicalMaterialLock> qw = new QueryWrapper<>();
        qw.eq("plan_date", Date.from(targetDate.atStartOfDay(ZoneId.systemDefault()).toInstant()))
                .like(trim(orderNo) != null, "order_no", trim(orderNo))
                .eq(trim(materialCode) != null, "finished_material_code", trim(materialCode))
                .orderByAsc("raw_material_code", "order_no", "id");

        List<ChemicalMaterialLock> locks = chemicalMaterialLockMapper.selectList(qw);
        if (locks == null || locks.isEmpty()) {
            return Collections.emptyList();
        }

        Map<Long, ChemicalStock> stockMap = new HashMap<>();
        List<Map<String, Object>> result = new ArrayList<>();
        for (ChemicalMaterialLock lock : locks) {
            if (lock == null) {
                continue;
            }

            Integer requiredQty = lock.getRequiredQty() == null ? 0 : lock.getRequiredQty();
            Integer lockedQty = lock.getLockedQty() == null ? 0 : lock.getLockedQty();
            int shortageQty = Math.max(requiredQty - lockedQty, 0);

            ChemicalStock stock = null;
            if (lock.getChemicalStockId() != null) {
                stock = stockMap.computeIfAbsent(lock.getChemicalStockId(), chemicalStockMapper::selectById);
            }

            Map<String, Object> row = new LinkedHashMap<>();
            row.put("id", lock.getId());
            row.put("planDate", lock.getPlanDate());
            row.put("scheduleId", lock.getScheduleId());
            row.put("orderNo", lock.getOrderNo());
            row.put("finishedMaterialCode", lock.getFinishedMaterialCode());
            row.put("rawMaterialCode", lock.getRawMaterialCode());
            row.put("rawMaterialName", lock.getRawMaterialName());
            row.put("chemicalStockId", lock.getChemicalStockId());
            row.put("requiredKg", lock.getRequiredKg());
            row.put("requiredQty", requiredQty);
            row.put("lockedQty", lockedQty);
            row.put("shortageQty", shortageQty);
            row.put("lockStatus", lock.getLockStatus());
            row.put("unit", stock != null && stock.getUnit() != null ? stock.getUnit() : "桶");
            row.put("stockAvailableQty", stock != null && stock.getAvailableQuantity() != null ? stock.getAvailableQuantity() : 0);
            row.put("updateTime", lock.getUpdateTime());
            result.add(row);
        }
        return result;
    }

    @Override
    public IPage<ChemicalPurchaseRequest> getRequestPage(int current, int size, String status) {
        Page<ChemicalPurchaseRequest> page = new Page<>(current, size);
        IPage<ChemicalPurchaseRequest> result = chemicalPurchaseRequestMapper.selectPageByStatus(page, trim(status));
        if (result != null && result.getRecords() != null) {
            for (ChemicalPurchaseRequest req : result.getRecords()) {
                if (req != null) {
                    req.setStatus(ChemicalRequisitionStatus.normalize(req.getStatus()));
                    req.setStatusText(ChemicalRequisitionStatus.labelOf(req.getStatus()));
                }
            }
        }
        return result;
    }

    @Override
    public ChemicalPurchaseRequest getRequestDetail(String requestNo) {
        ChemicalPurchaseRequest req = chemicalPurchaseRequestMapper.selectByRequestNo(requestNo);
        if (req == null) {
            return null;
        }
        req.setStatus(ChemicalRequisitionStatus.normalize(req.getStatus()));
        req.setStatusText(ChemicalRequisitionStatus.labelOf(req.getStatus()));
        req.setItems(chemicalPurchaseRequestItemMapper.selectByRequestId(req.getId()));
        req.setLogs(chemicalRequisitionLogMapper.selectByRequestNo(requestNo));
        return req;
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void updateRequestedQty(Long itemId, Integer requestedQty) {
        if (itemId == null || requestedQty == null || requestedQty < 0) {
            throw new RuntimeException("参数无效");
        }

        ChemicalPurchaseRequestItem item = chemicalPurchaseRequestItemMapper.selectById(itemId);
        if (item == null || item.getRequestId() == null) {
            throw new RuntimeException("请购明细不存在");
        }
        ChemicalPurchaseRequest req = chemicalPurchaseRequestMapper.selectById(item.getRequestId());
        if (req == null) {
            throw new RuntimeException("请购单不存在");
        }
        String status = ChemicalRequisitionStatus.normalize(req.getStatus());
        if (!(ChemicalRequisitionStatus.DRAFT.equals(status) || ChemicalRequisitionStatus.SUBMITTED.equals(status))) {
            throw new RuntimeException("当前状态不允许修改请购数量");
        }

        int ok = chemicalPurchaseRequestItemMapper.updateRequestedQty(itemId, requestedQty);
        if (ok <= 0) {
            throw new RuntimeException("更新失败");
        }
        appendLog(req.getRequestNo(), req.getId(), "UPDATE_QTY", "warehouse", "更新请购数量 itemId=" + itemId + ", requestedQty=" + requestedQty);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void submitRequest(String requestNo) {
        ChemicalPurchaseRequest req = chemicalPurchaseRequestMapper.selectByRequestNo(requestNo);
        if (req == null) {
            throw new RuntimeException("请购单不存在");
        }
        String currentStatus = ChemicalRequisitionStatus.normalize(req.getStatus());
        if (!ChemicalRequisitionStatus.DRAFT.equals(currentStatus)) {
            throw new RuntimeException("仅草稿状态可提交");
        }
        chemicalPurchaseRequestMapper.updateStatus(requestNo, ChemicalRequisitionStatus.SUBMITTED, "warehouse");
        appendLog(requestNo, req.getId(), "SUBMIT", "warehouse", "提交请购单");
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void approveRequest(String requestNo) {
        ChemicalPurchaseRequest req = chemicalPurchaseRequestMapper.selectByRequestNo(requestNo);
        if (req == null) {
            throw new RuntimeException("请购单不存在");
        }
        String currentStatus = ChemicalRequisitionStatus.normalize(req.getStatus());
        if (!ChemicalRequisitionStatus.SUBMITTED.equals(currentStatus)) {
            throw new RuntimeException("当前状态不允许审核");
        }
        chemicalPurchaseRequestMapper.updateStatus(requestNo, ChemicalRequisitionStatus.APPROVED, "warehouse");
        appendLog(requestNo, req.getId(), "APPROVE", "warehouse", "审核通过");
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public String createPurchaseOrder(String requestNo) {
        ChemicalPurchaseRequest req = chemicalPurchaseRequestMapper.selectByRequestNo(requestNo);
        if (req == null) {
            throw new RuntimeException("请购单不存在");
        }
        if (!ChemicalRequisitionStatus.APPROVED.equals(ChemicalRequisitionStatus.normalize(req.getStatus()))) {
            throw new RuntimeException("仅已审核状态可转采购");
        }
        if (req.getPurchaseOrderNo() != null && !req.getPurchaseOrderNo().trim().isEmpty()) {
            return req.getPurchaseOrderNo();
        }

        List<ChemicalPurchaseRequestItem> items = chemicalPurchaseRequestItemMapper.selectByRequestId(req.getId());
        if (items == null || items.isEmpty()) {
            throw new RuntimeException("请购明细为空");
        }

        BigDecimal totalQty = BigDecimal.ZERO;
        for (ChemicalPurchaseRequestItem item : items) {
            Integer qty = item.getRequestedQty() == null ? 0 : item.getRequestedQty();
            if (qty > 0) {
                totalQty = totalQty.add(BigDecimal.valueOf(qty));
            }
        }

        PurchaseOrder po = new PurchaseOrder();
        po.setOrderNo(generatePurchaseOrderNo());
        po.setSupplier("AUTO-CHEMICAL");
        po.setOrderDate(Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant()));
        po.setDeliveryDate(Date.from(LocalDate.now().plusDays(7).atStartOfDay(ZoneId.systemDefault()).toInstant()));
        po.setStatus("pending");
        po.setRemark("source=chemical_purchase_request;requestNo=" + requestNo);
        po.setCreatedBy("system");
        po.setUpdatedBy("system");
        po.setCreatedAt(new Date());
        po.setUpdatedAt(new Date());
        po.setIsDeleted(0);
        po.setTotalAmount(BigDecimal.ZERO);
        po.setTotalArea(totalQty);
        po.setRequiredArea(totalQty);
        purchaseOrderMapper.insert(po);

        for (ChemicalPurchaseRequestItem reqItem : items) {
            int qty = reqItem.getRequestedQty() == null ? 0 : reqItem.getRequestedQty();
            if (qty <= 0) {
                continue;
            }
            PurchaseOrderItem poi = new PurchaseOrderItem();
            poi.setOrderId(po.getId());
            poi.setMaterialCode(reqItem.getRawMaterialCode());
            poi.setMaterialName(reqItem.getRawMaterialName());
            poi.setRolls(qty);
            poi.setSqm(BigDecimal.valueOf(qty));
            poi.setUnitPrice(BigDecimal.ZERO);
            poi.setAmount(BigDecimal.ZERO);
            poi.setRemark("linkedRequest=" + requestNo + ";requestItemId=" + reqItem.getId());
            poi.setCreatedBy("system");
            poi.setUpdatedBy("system");
            poi.setCreatedAt(new Date());
            poi.setUpdatedAt(new Date());
            poi.setIsDeleted(0);
            purchaseOrderItemMapper.insert(poi);
            chemicalPurchaseRequestItemMapper.updatePurchaseOrderItemId(reqItem.getId(), poi.getId());
        }

        chemicalPurchaseRequestMapper.updatePurchaseOrderNo(requestNo, po.getOrderNo(), "warehouse");
        chemicalPurchaseRequestMapper.updateStatus(requestNo, ChemicalRequisitionStatus.PO_CREATED, "warehouse");
        appendLog(requestNo, req.getId(), "CREATE_PO", "warehouse", "生成采购单: " + po.getOrderNo());
        return po.getOrderNo();
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public Map<String, Object> receiveAndFulfill(String requestNo, Map<Long, Integer> receiveQtyMap) {
        ChemicalPurchaseRequest req = chemicalPurchaseRequestMapper.selectByRequestNo(requestNo);
        if (req == null) {
            throw new RuntimeException("请购单不存在");
        }
        String currentStatus = ChemicalRequisitionStatus.normalize(req.getStatus());
        if (!Arrays.asList(ChemicalRequisitionStatus.PO_CREATED,
                ChemicalRequisitionStatus.PARTIAL_RECEIVED,
                ChemicalRequisitionStatus.RECEIVED).contains(currentStatus)) {
            throw new RuntimeException("当前状态不允许收货");
        }
        if (ChemicalRequisitionStatus.RECEIVED.equals(currentStatus)) {
            Map<String, Object> done = new LinkedHashMap<>();
            done.put("receivedQty", 0);
            done.put("fulfilledQty", 0);
            done.put("message", "该请购单已入库");
            return done;
        }

        List<ChemicalPurchaseRequestItem> items = chemicalPurchaseRequestItemMapper.selectByRequestId(req.getId());
        if (items == null || items.isEmpty()) {
            throw new RuntimeException("请购明细为空");
        }

        int totalReceived = 0;
        int totalFulfilled = 0;
        Map<Long, Integer> qtyMap = receiveQtyMap == null ? Collections.emptyMap() : receiveQtyMap;
        boolean hasExplicitQty = !qtyMap.isEmpty();

        for (ChemicalPurchaseRequestItem item : items) {
            if (item == null || item.getRawMaterialCode() == null || item.getRawMaterialCode().trim().isEmpty()) {
                continue;
            }
            int defaultReceive = item.getRequestedQty() == null ? 0 : item.getRequestedQty();
            int alreadyReceived = item.getReceivedQty() == null ? 0 : item.getReceivedQty();
            int remainingReceivable = Math.max(defaultReceive - alreadyReceived, 0);
            int receiveQty = qtyMap.containsKey(item.getId()) ? Math.max(qtyMap.get(item.getId()), 0) : remainingReceivable;
            if (receiveQty > remainingReceivable) {
                throw new RuntimeException("物料 " + item.getRawMaterialCode() + " 本次实收数量不能大于剩余待收数量");
            }
            if (receiveQty <= 0) {
                continue;
            }

            ChemicalStock stock = ensureChemicalStockByCode(item.getRawMaterialCode().trim(), item.getRawMaterialName(), item.getUnit());
            int inOk = chemicalStockMapper.addStock(stock.getId(), receiveQty);
            if (inOk <= 0) {
                throw new RuntimeException("化工入库失败，物料：" + item.getRawMaterialCode());
            }
            totalReceived += receiveQty;
            chemicalPurchaseRequestItemMapper.updateReceivedQty(item.getId(), alreadyReceived + receiveQty);

            int fulfilled = fulfillLocksForItem(stock.getId(), item, receiveQty);
            totalFulfilled += fulfilled;
            appendLog(requestNo, req.getId(), "RECEIVE_ITEM", "warehouse",
                    "明细到货 itemId=" + item.getId() + ", raw=" + item.getRawMaterialCode() + ", receiveQty=" + receiveQty + ", fulfilled=" + fulfilled);
        }

        if (hasExplicitQty && totalReceived <= 0) {
            throw new RuntimeException("请填写本次实收数量");
        }

        boolean allReceived = true;
        List<ChemicalPurchaseRequestItem> latestItems = chemicalPurchaseRequestItemMapper.selectByRequestId(req.getId());
        for (ChemicalPurchaseRequestItem latest : latestItems) {
            int reqQty = latest.getRequestedQty() == null ? 0 : latest.getRequestedQty();
            int recQty = latest.getReceivedQty() == null ? 0 : latest.getReceivedQty();
            if (recQty < reqQty) {
                allReceived = false;
                break;
            }
        }
        chemicalPurchaseRequestMapper.updateStatus(requestNo,
            allReceived ? ChemicalRequisitionStatus.RECEIVED : ChemicalRequisitionStatus.PARTIAL_RECEIVED,
            "warehouse");
        appendLog(requestNo, req.getId(), "RECEIVE", "warehouse", "到货入库完成, receivedQty=" + totalReceived + ", fulfilledQty=" + totalFulfilled);
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("receivedQty", totalReceived);
        result.put("fulfilledQty", totalFulfilled);
        result.put("message", allReceived ? "全部到货入库并回填完成" : "部分到货入库并回填完成");
        return result;
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public Map<String, Object> confirmIssueByLocks(List<Long> lockIds, String operator) {
        if (lockIds == null || lockIds.isEmpty()) {
            throw new RuntimeException("锁定记录不能为空");
        }

        int issuedCount = 0;
        int skippedCount = 0;
        int totalQty = 0;
        BigDecimal totalWeight = BigDecimal.ZERO;

        String user = trim(operator) == null ? "production" : trim(operator);
        for (Long lockId : lockIds) {
            if (lockId == null) {
                continue;
            }
            ChemicalMaterialLock lock = chemicalMaterialLockMapper.selectById(lockId);
            if (lock == null) {
                skippedCount++;
                continue;
            }

            String status = str(lock.getLockStatus());
            if ("ALLOCATED".equalsIgnoreCase(status)) {
                skippedCount++;
                continue;
            }
            if (!("LOCKED".equalsIgnoreCase(status) || "PARTIAL".equalsIgnoreCase(status))) {
                skippedCount++;
                continue;
            }

            int outQty = lock.getLockedQty() == null ? 0 : lock.getLockedQty();
            if (outQty <= 0 || lock.getChemicalStockId() == null) {
                skippedCount++;
                continue;
            }

            BigDecimal outWeight = BigDecimal.ZERO;
            BigDecimal requiredKg = lock.getRequiredKg() == null ? BigDecimal.ZERO : lock.getRequiredKg();
            int requiredQty = lock.getRequiredQty() == null ? 0 : lock.getRequiredQty();
            if (requiredQty > 0 && requiredKg.compareTo(BigDecimal.ZERO) > 0) {
                outWeight = requiredKg.multiply(BigDecimal.valueOf(outQty))
                        .divide(BigDecimal.valueOf(requiredQty), 3, RoundingMode.HALF_UP);
            }

            ChemicalStockOut out = new ChemicalStockOut();
            out.setChemicalStockId(lock.getChemicalStockId());
            out.setOutboundNo("CHOUT" + LocalDate.now().format(DateTimeFormatter.ofPattern("yyMMdd")) + "-" + lock.getId());
            out.setOutQuantity(outQty);
            out.setOutWeight(outWeight);
            out.setScheduleId(lock.getScheduleId());
            out.setPurpose("COATING_MATERIAL_ISSUE");
            out.setOutboundBy(user);
            out.setOutboundTime(new Date());
            out.setRemark("source=coating-task-issue;orderNo=" + (lock.getOrderNo() == null ? "" : lock.getOrderNo()));

            // 化工出库（会扣减 locked_quantity，并写出库记录）
            chemicalStockService.outbound(out, null);

            lock.setLockStatus("ALLOCATED");
            lock.setUpdateTime(new Date());
            chemicalMaterialLockMapper.updateById(lock);

            issuedCount++;
            totalQty += outQty;
            totalWeight = totalWeight.add(outWeight);
        }

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("issuedCount", issuedCount);
        result.put("skippedCount", skippedCount);
        result.put("totalOutQty", totalQty);
        result.put("totalOutWeight", totalWeight.setScale(3, RoundingMode.HALF_UP));
        return result;
    }

    private void appendLog(String requestNo, Long requestId, String actionType, String operator, String content) {
        ChemicalRequisitionLog log = new ChemicalRequisitionLog();
        log.setRequestNo(requestNo);
        log.setRequestId(requestId);
        log.setActionType(actionType);
        log.setOperator(operator == null ? "system" : operator);
        log.setContent(content);
        log.setCreateTime(new Date());
        chemicalRequisitionLogMapper.insert(log);
    }

    private ChemicalStock ensureChemicalStockByCode(String materialCode, String materialName, String unit) {
        QueryWrapper<ChemicalStock> qw = new QueryWrapper<>();
        qw.eq("material_code", materialCode).last("LIMIT 1");
        ChemicalStock stock = chemicalStockMapper.selectOne(qw);
        if (stock != null) {
            return stock;
        }

        ChemicalStock created = new ChemicalStock();
        created.setMaterialCode(materialCode);
        created.setMaterialName(materialName == null || materialName.trim().isEmpty() ? materialCode : materialName.trim());
        created.setChemicalType("other");
        created.setUnit(unit == null || unit.trim().isEmpty() ? "桶" : unit.trim());
        created.setUnitWeight(BigDecimal.ONE);
        created.setTotalQuantity(0);
        created.setAvailableQuantity(0);
        created.setLockedQuantity(0);
        created.setSafetyStock(0);
        created.setStatus("active");
        created.setRemark("auto-create-by-chemical-receive");
        created.setCreateTime(new Date());
        created.setUpdateTime(new Date());
        created.setCreateBy("system");
        created.setUpdateBy("system");
        chemicalStockMapper.insert(created);
        return created;
    }

    private int fulfillLocksForItem(Long stockId, ChemicalPurchaseRequestItem item, int receiveQty) {
        int remain = receiveQty;
        int fulfilled = 0;
        if (remain <= 0) {
            return 0;
        }

        QueryWrapper<ChemicalMaterialLock> qw = new QueryWrapper<>();
        qw.eq("raw_material_code", item.getRawMaterialCode())
                .eq(item.getScheduleId() != null, "schedule_id", item.getScheduleId())
                .eq(item.getOrderNo() != null && !item.getOrderNo().trim().isEmpty(), "order_no", item.getOrderNo())
                .in("lock_status", Arrays.asList("PENDING", "PARTIAL"))
                .orderByAsc("id");

        List<ChemicalMaterialLock> locks = chemicalMaterialLockMapper.selectList(qw);
        for (ChemicalMaterialLock lock : locks) {
            if (remain <= 0) {
                break;
            }
            int required = lock.getRequiredQty() == null ? 0 : lock.getRequiredQty();
            int already = lock.getLockedQty() == null ? 0 : lock.getLockedQty();
            int need = required - already;
            if (need <= 0) {
                lock.setLockStatus("LOCKED");
                chemicalMaterialLockMapper.updateById(lock);
                continue;
            }
            int add = Math.min(remain, need);
            if (add <= 0) {
                continue;
            }
            int lockOk = chemicalStockMapper.lockStock(stockId, add);
            if (lockOk <= 0) {
                break;
            }

            lock.setChemicalStockId(stockId);
            lock.setLockedQty(already + add);
            lock.setLockStatus(lock.getLockedQty() >= required ? "LOCKED" : "PARTIAL");
            lock.setUpdateTime(new Date());
            chemicalMaterialLockMapper.updateById(lock);
            remain -= add;
            fulfilled += add;
        }
        return fulfilled;
    }

    private String generatePurchaseOrderNo() {
        String dateCode = LocalDate.now().format(DateTimeFormatter.ofPattern("yyMMdd"));
        String prefix = "CD" + dateCode;
        String last = purchaseOrderMapper.selectLastOrderNoByPrefix(prefix);
        int nextSeq = 1;
        if (last != null && last.length() > prefix.length()) {
            try {
                nextSeq = Integer.parseInt(last.substring(prefix.length())) + 1;
            } catch (Exception ignore) {
                nextSeq = 1;
            }
        }
        return prefix + String.format("%02d", nextSeq);
    }

    private ChemicalPurchaseRequest ensureDraftRequest(LocalDate planDate, Long scheduleId, String orderNo, String finishedCode) {
        QueryWrapper<ChemicalPurchaseRequest> findQw = new QueryWrapper<>();
        findQw.eq("is_deleted", 0)
                .eq(scheduleId != null, "schedule_id", scheduleId)
                .eq(orderNo != null && !orderNo.trim().isEmpty(), "order_no", orderNo)
                .eq(finishedCode != null && !finishedCode.trim().isEmpty(), "finished_material_code", finishedCode)
                .eq("source", "coating-lock-query")
                .orderByDesc("id")
                .last("LIMIT 1");
        ChemicalPurchaseRequest byBizKey = chemicalPurchaseRequestMapper.selectOne(findQw);
        if (byBizKey != null) {
            return byBizKey;
        }

        String schedulePart = scheduleId == null ? "TB0" : ("TB" + scheduleId);
        String orderPart = orderNo == null ? "NO" : orderNo.replaceAll("[^A-Za-z0-9]", "");
        String requestNo = "CPR" + planDate.format(DateTimeFormatter.ofPattern("yyMMdd")) + "-" + schedulePart + "-" + orderPart;
        ChemicalPurchaseRequest exists = chemicalPurchaseRequestMapper.selectByRequestNo(requestNo);
        if (exists != null) {
            return exists;
        }
        ChemicalPurchaseRequest req = new ChemicalPurchaseRequest();
        req.setRequestNo(requestNo);
        req.setPlanDate(Date.from(planDate.atStartOfDay(ZoneId.systemDefault()).toInstant()));
        req.setScheduleId(scheduleId);
        req.setOrderNo(orderNo);
        req.setFinishedMaterialCode(finishedCode);
        req.setStatus(ChemicalRequisitionStatus.DRAFT);
        req.setSource("coating-lock-query");
        req.setRemark("按配胶标准自动生成");
        req.setCreateTime(new Date());
        req.setUpdateTime(new Date());
        req.setCreateBy("system");
        req.setUpdateBy("system");
        req.setIsDeleted(0);
        chemicalPurchaseRequestMapper.insert(req);
        return req;
    }

    private ChemicalStock pickChemicalStock(String rawCode) {
        QueryWrapper<ChemicalStock> qw = new QueryWrapper<>();
        qw.eq("material_code", rawCode)
                .in("status", Arrays.asList("active", "low_stock"))
                .gt("available_quantity", 0)
                .orderByDesc("available_quantity")
                .last("LIMIT 1");
        return chemicalStockMapper.selectOne(qw);
    }

    private void cleanupAutoGeneratedForSchedule(Long requestId, Long scheduleId, String orderNo, String finishedCode) {
        if (scheduleId == null) {
            return;
        }

        QueryWrapper<ChemicalMaterialLock> lockQw = new QueryWrapper<>();
        lockQw.eq("schedule_id", scheduleId)
                .eq(orderNo != null && !orderNo.trim().isEmpty(), "order_no", orderNo)
                .eq(finishedCode != null && !finishedCode.trim().isEmpty(), "finished_material_code", finishedCode)
                .eq("remark", "auto-generate-on-lock-query");
        List<ChemicalMaterialLock> oldLocks = chemicalMaterialLockMapper.selectList(lockQw);
        if (oldLocks != null && !oldLocks.isEmpty()) {
            List<Long> deletableIds = new ArrayList<>();
            for (ChemicalMaterialLock old : oldLocks) {
                if (old == null) {
                    continue;
                }

                // 已领料记录保留，避免重复请购/重复锁定
                if ("ALLOCATED".equalsIgnoreCase(str(old.getLockStatus()))) {
                    continue;
                }

                int lockedQty = old.getLockedQty() == null ? 0 : old.getLockedQty();
                if (lockedQty > 0 && old.getChemicalStockId() != null) {
                    chemicalStockMapper.unlockStock(old.getChemicalStockId(), lockedQty);
                }
                deletableIds.add(old.getId());
            }
            if (!deletableIds.isEmpty()) {
                chemicalMaterialLockMapper.deleteBatchIds(deletableIds);
            }
        }

        if (requestId != null) {
            QueryWrapper<ChemicalPurchaseRequestItem> itemQw = new QueryWrapper<>();
            itemQw.eq("request_id", requestId)
                    .eq("schedule_id", scheduleId)
                    .eq(orderNo != null && !orderNo.trim().isEmpty(), "order_no", orderNo)
                    .eq(finishedCode != null && !finishedCode.trim().isEmpty(), "finished_material_code", finishedCode)
                    .eq("remark", "库存不足自动请购");
            chemicalPurchaseRequestItemMapper.delete(itemQw);
        }
    }

    private boolean hasAllocatedAutoLocks(Long scheduleId, String orderNo, String finishedCode) {
        if (scheduleId == null) {
            return false;
        }
        QueryWrapper<ChemicalMaterialLock> qw = new QueryWrapper<>();
        qw.eq("schedule_id", scheduleId)
                .eq(orderNo != null && !orderNo.trim().isEmpty(), "order_no", orderNo)
                .eq(finishedCode != null && !finishedCode.trim().isEmpty(), "finished_material_code", finishedCode)
                .eq("remark", "auto-generate-on-lock-query")
                .eq("lock_status", "ALLOCATED")
                .last("LIMIT 1");
        return chemicalMaterialLockMapper.selectOne(qw) != null;
    }

    private BigDecimal calcNeedKg(TapeFormulaItem item, BigDecimal factor, BigDecimal totalWeight) {
        BigDecimal need = BigDecimal.ZERO;
        if (item.getWeight() != null && item.getWeight().compareTo(BigDecimal.ZERO) > 0) {
            need = item.getWeight().multiply(factor);
        } else if (item.getRatio() != null && item.getRatio().compareTo(BigDecimal.ZERO) > 0 && totalWeight.compareTo(BigDecimal.ZERO) > 0) {
            need = totalWeight.multiply(item.getRatio())
                    .divide(new BigDecimal("100"), 8, RoundingMode.HALF_UP)
                    .multiply(factor);
        }
        return need.setScale(3, RoundingMode.HALF_UP);
    }

    private int convertKgToQty(BigDecimal needKg, ChemicalStock stock) {
        if (needKg == null || needKg.compareTo(BigDecimal.ZERO) <= 0) {
            return 0;
        }
        BigDecimal unitWeight = (stock == null || stock.getUnitWeight() == null || stock.getUnitWeight().compareTo(BigDecimal.ZERO) <= 0)
                ? BigDecimal.ONE : stock.getUnitWeight();
        return needKg.divide(unitWeight, 0, RoundingMode.CEILING).intValue();
    }

    private Map<String, Object> resultMap(int lockCount, int reqCount, Set<String> requestNos, List<Map<String, Object>> missingFormulaPlans) {
        Map<String, Object> res = new LinkedHashMap<>();
        res.put("lockCount", lockCount);
        res.put("requestItemCount", reqCount);
        res.put("requestNos", new ArrayList<>(requestNos));
        List<Map<String, Object>> missing = missingFormulaPlans == null ? Collections.emptyList() : missingFormulaPlans;
        res.put("missingFormulaCount", missing.size());
        res.put("missingFormulaPlans", missing);
        return res;
    }

    private Map<String, Object> buildMissingFormulaRow(Long scheduleId,
                                                       String orderNo,
                                                       String finishedCode,
                                                       String finishedName,
                                                       String reason) {
        Map<String, Object> row = new LinkedHashMap<>();
        row.put("scheduleId", scheduleId);
        row.put("orderNo", orderNo);
        row.put("materialCode", finishedCode);
        row.put("materialName", finishedName);
        row.put("reason", reason);
        return row;
    }

    private String trim(String s) {
        if (s == null) {
            return null;
        }
        String t = s.trim();
        return t.isEmpty() ? null : t;
    }

    private String str(Object obj) {
        return obj == null ? null : String.valueOf(obj);
    }

    private Long toLong(Object obj) {
        if (obj == null) {
            return null;
        }
        if (obj instanceof Number) {
            return ((Number) obj).longValue();
        }
        try {
            return Long.parseLong(String.valueOf(obj));
        } catch (Exception e) {
            return null;
        }
    }

    private BigDecimal toDecimal(Object obj) {
        if (obj == null) {
            return BigDecimal.ZERO;
        }
        try {
            return new BigDecimal(String.valueOf(obj));
        } catch (Exception e) {
            return BigDecimal.ZERO;
        }
    }
}
