spring.application.name=MES
server.port=8090

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://ssdw8127.mysql.rds.aliyuncs.com/erp?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=david
spring.datasource.password=dadazhengzheng@feng

spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.validation-timeout=250
#logging.level.org.springframework.security=DEBUG
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# application.properties
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0
mybatis-plus.global-config.banner=false

# MyBatis Plus 配置
mybatis-plus.mapper-locations=classpath:mapper/**/*.xml



