CREATE TABLE IF NOT EXISTS `rewinding_coding_inbound` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `batch_no` VARCHAR(64) NOT NULL COMMENT '同一次母卷录入批次号',
  `mother_roll_code` VARCHAR(128) NOT NULL COMMENT '母卷号',
  `mother_stock_id` BIGINT NULL COMMENT '母卷库存ID',
  `material_code` VARCHAR(128) NULL,
  `material_name` VARCHAR(255) NULL,
  `mother_thickness` INT NULL COMMENT '母卷厚度(μm)',
  `mother_width_mm` INT NULL COMMENT '母卷宽度(mm)',
  `mother_length_m` DECIMAL(18,3) NULL COMMENT '母卷长度(m)',
  `rewinding_length_m` DECIMAL(18,3) NOT NULL COMMENT '复卷长度(m)',
  `rewinding_roll_count` INT NOT NULL DEFAULT 1 COMMENT '复卷卷数',
  `rewinding_spec` VARCHAR(128) NOT NULL COMMENT '厚度*宽度*长度',
  `line_no` INT NOT NULL,
  `serial_start` INT NOT NULL DEFAULT 1,
  `print_count` INT NOT NULL DEFAULT 1,
  `operator` VARCHAR(64) NULL COMMENT '复卷人',
  `visible_fields` VARCHAR(255) NULL COMMENT '标签可见字段CSV',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_batch_no` (`batch_no`),
  KEY `idx_mother_roll_code` (`mother_roll_code`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='复卷打码入库记录';
