CREATE TABLE IF NOT EXISTS stocktake_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  warehouse_type VARCHAR(32) NOT NULL COMMENT '仓库类型：TAPE/FILM/CHEMICAL/PACKAGE',
  stock_id BIGINT NOT NULL COMMENT '库存主表ID',
  detail_id BIGINT NULL COMMENT '库存明细ID；胶带仓直接为主表ID',
  material_code VARCHAR(100) NULL COMMENT '物料代码',
  material_name VARCHAR(255) NULL COMMENT '物料名称',
  spec_desc VARCHAR(255) NULL COMMENT '规格',
  batch_no VARCHAR(100) NULL COMMENT '批次号',
  container_no VARCHAR(100) NULL COMMENT '容器/卷号',
  location VARCHAR(100) NULL COMMENT '存放位置',
  unit VARCHAR(32) NULL COMMENT '单位',
  before_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '盘点前数量',
  after_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '实盘数量',
  diff_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '差异数量',
  change_status VARCHAR(20) NOT NULL COMMENT 'UNCHANGED/PROFIT/LOSS',
  operator VARCHAR(100) NULL COMMENT '盘点人',
  reason VARCHAR(255) NULL COMMENT '盘点原因',
  remark VARCHAR(500) NULL COMMENT '备注',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_warehouse_material (warehouse_type, material_code),
  KEY idx_stock_detail (warehouse_type, stock_id, detail_id),
  KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存盘点记录表';

CREATE TABLE IF NOT EXISTS stock_profit_loss_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  stocktake_record_id BIGINT NOT NULL COMMENT '盘点记录ID',
  warehouse_type VARCHAR(32) NOT NULL COMMENT '仓库类型：TAPE/FILM/CHEMICAL/PACKAGE',
  stock_id BIGINT NOT NULL COMMENT '库存主表ID',
  detail_id BIGINT NULL COMMENT '库存明细ID；胶带仓直接为主表ID',
  material_code VARCHAR(100) NULL COMMENT '物料代码',
  material_name VARCHAR(255) NULL COMMENT '物料名称',
  spec_desc VARCHAR(255) NULL COMMENT '规格',
  batch_no VARCHAR(100) NULL COMMENT '批次号',
  container_no VARCHAR(100) NULL COMMENT '容器/卷号',
  location VARCHAR(100) NULL COMMENT '存放位置',
  unit VARCHAR(32) NULL COMMENT '单位',
  before_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '盘点前数量',
  after_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '实盘数量',
  diff_quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '差异数量',
  profit_loss_type VARCHAR(20) NOT NULL COMMENT 'PROFIT/LOSS',
  operator VARCHAR(100) NULL COMMENT '盘点人',
  reason VARCHAR(255) NULL COMMENT '盘点原因',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_stocktake_record_id (stocktake_record_id),
  KEY idx_warehouse_material (warehouse_type, material_code),
  KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存盘盈盘亏记录表';