USE erp;

-- 薄膜明细表
CREATE TABLE IF NOT EXISTS film_stock_detail (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    stock_id BIGINT NOT NULL,
    material_code VARCHAR(50) NOT NULL,
    batch_no VARCHAR(50) NOT NULL,
    roll_no VARCHAR(50),
    thickness DECIMAL(10,3) NOT NULL,
    width INT NOT NULL,
    length INT,
    diameter INT,
    core_diameter INT DEFAULT 76,
    weight DECIMAL(10,2),
    area DECIMAL(10,2),
    quality_level VARCHAR(20) DEFAULT 'A',
    quality_status VARCHAR(20) DEFAULT 'qualified',
    defect_desc VARCHAR(200),
    warehouse VARCHAR(50) DEFAULT '原料仓',
    location VARCHAR(50),
    supplier VARCHAR(100),
    purchase_order_no VARCHAR(50),
    arrival_date DATE,
    storage_date DATE,
    unit_price DECIMAL(10,4),
    status VARCHAR(20) DEFAULT 'available',
    locked_by VARCHAR(50),
    locked_time DATETIME,
    remark VARCHAR(500),
    create_by VARCHAR(50),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_by VARCHAR(50),
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT DEFAULT 0,
    INDEX idx_stock_id (stock_id),
    INDEX idx_batch_no (batch_no),
    INDEX idx_material_code (material_code),
    INDEX idx_status (status),
    UNIQUE KEY uk_roll_no (roll_no)
);

-- 化工总量表
CREATE TABLE IF NOT EXISTS chemical_stock (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    material_code VARCHAR(50) NOT NULL,
    material_name VARCHAR(100) NOT NULL,
    chemical_type VARCHAR(50),
    unit VARCHAR(20) DEFAULT '桶',
    unit_weight DECIMAL(10,2),
    total_quantity INT DEFAULT 0,
    total_weight DECIMAL(12,2) DEFAULT 0,
    available_quantity INT DEFAULT 0,
    available_weight DECIMAL(12,2) DEFAULT 0,
    locked_quantity INT DEFAULT 0,
    locked_weight DECIMAL(12,2) DEFAULT 0,
    last_in_date DATE,
    last_out_date DATE,
    remark VARCHAR(500),
    create_by VARCHAR(50),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_by VARCHAR(50),
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT DEFAULT 0,
    UNIQUE KEY uk_material_code (material_code),
    INDEX idx_chemical_type (chemical_type)
);

-- 化工明细表
CREATE TABLE IF NOT EXISTS chemical_stock_detail (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    stock_id BIGINT NOT NULL,
    material_code VARCHAR(50) NOT NULL,
    batch_no VARCHAR(50) NOT NULL,
    barrel_no VARCHAR(50),
    unit VARCHAR(20) DEFAULT '桶',
    weight DECIMAL(10,2),
    net_weight DECIMAL(10,2),
    remaining_weight DECIMAL(10,2),
    quality_level VARCHAR(20) DEFAULT 'A',
    quality_status VARCHAR(20) DEFAULT 'qualified',
    production_date DATE,
    expiry_date DATE,
    warehouse VARCHAR(50) DEFAULT '化工仓',
    location VARCHAR(50),
    supplier VARCHAR(100),
    purchase_order_no VARCHAR(50),
    arrival_date DATE,
    storage_date DATE,
    unit_price DECIMAL(10,2),
    status VARCHAR(20) DEFAULT 'available',
    is_opened TINYINT DEFAULT 0,
    locked_by VARCHAR(50),
    locked_time DATETIME,
    danger_level VARCHAR(20),
    msds_file VARCHAR(200),
    remark VARCHAR(500),
    create_by VARCHAR(50),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_by VARCHAR(50),
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT DEFAULT 0,
    INDEX idx_stock_id (stock_id),
    INDEX idx_batch_no (batch_no),
    INDEX idx_material_code (material_code),
    INDEX idx_status (status),
    INDEX idx_expiry_date (expiry_date),
    UNIQUE KEY uk_barrel_no (barrel_no)
);

-- 修改涂布任务表（先检查列是否存在，如不存在则添加）
-- 注意：MySQL 5.7不支持 IF NOT EXISTS，需要手动处理


-- 薄膜出库记录表
CREATE TABLE IF NOT EXISTS film_stock_out (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    out_no VARCHAR(50) NOT NULL,
    stock_id BIGINT NOT NULL,
    detail_id BIGINT NOT NULL,
    material_code VARCHAR(50) NOT NULL,
    batch_no VARCHAR(50) NOT NULL,
    roll_no VARCHAR(50),
    out_area DECIMAL(10,2) NOT NULL,
    out_date DATETIME NOT NULL,
    out_type VARCHAR(20) DEFAULT 'production',
    schedule_id BIGINT,
    coating_task_id BIGINT,
    operator VARCHAR(50),
    receiver VARCHAR(50),
    department VARCHAR(50),
    remark VARCHAR(500),
    create_by VARCHAR(50),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_out_no (out_no),
    INDEX idx_stock_id (stock_id),
    INDEX idx_detail_id (detail_id),
    INDEX idx_schedule_id (schedule_id),
    INDEX idx_coating_task_id (coating_task_id)
);

-- 化工出库记录表
CREATE TABLE IF NOT EXISTS chemical_stock_out (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    out_no VARCHAR(50) NOT NULL,
    stock_id BIGINT NOT NULL,
    detail_id BIGINT NOT NULL,
    material_code VARCHAR(50) NOT NULL,
    batch_no VARCHAR(50) NOT NULL,
    barrel_no VARCHAR(50),
    out_weight DECIMAL(10,2) NOT NULL,
    out_date DATETIME NOT NULL,
    out_type VARCHAR(20) DEFAULT 'production',
    schedule_id BIGINT,
    coating_task_id BIGINT,
    operator VARCHAR(50),
    receiver VARCHAR(50),
    department VARCHAR(50),
    remark VARCHAR(500),
    create_by VARCHAR(50),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_out_no (out_no),
    INDEX idx_stock_id (stock_id),
    INDEX idx_detail_id (detail_id),
    INDEX idx_schedule_id (schedule_id)
);
